<a href="https://colab.research.google.com/github/umeshku1994/HELLO-WORLD/blob/master/Sample_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.random.rand(5,5)

array([[0.58791208, 0.55104991, 0.12273061, 0.52015921, 0.69473995],
       [0.18661505, 0.08319826, 0.87156869, 0.61868732, 0.80061338],
       [0.50265317, 0.64601599, 0.7450206 , 0.63087287, 0.49386208],
       [0.62286803, 0.19915459, 0.10892445, 0.44502222, 0.94995111],
       [0.02798135, 0.62541876, 0.64493609, 0.85902135, 0.1315596 ]])

In [5]:
#gaussian distribution
np.random.randn(5,5)

array([[ 1.80234164,  1.08352647,  1.52035016,  0.64950212, -1.28160082],
       [-1.3054045 , -0.91832549, -0.85402712,  0.7421728 ,  0.1182464 ],
       [-0.12569688,  1.8129079 , -0.40403152,  0.10226653, -1.62725596],
       [ 0.517216  , -0.9808218 , -1.12411655,  0.32252509,  2.50566007],
       [ 0.66828154, -0.27849671,  0.96285165, -1.20086704, -0.96182591]])

In [9]:
#generate random number between given numbers
np.random.randint(0,100,10)

array([30, 32, 31, 74, 81, 61, 95, 44, 30, 61])

In [11]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
ranarr=np.random.randint(1,100,19)
ranarr

array([27, 29, 55,  5, 90, 20, 37, 14, 55, 47, 92,  8, 76, 94,  9, 22, 37,
        1, 80])

In [23]:
#reshape as new dimensions specified, 5*5 below
reshaped_arr=arr.reshape(5,5)

In [18]:
#max value from array
ranarr.max()

94

In [19]:
#index of max value
ranarr.argmax()

13

In [20]:
ranarr.argmin()

17

In [22]:
arr.shape

(25,)

In [24]:
reshaped_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#datatype of array
arr.dtype

dtype('int64')

In [30]:
from numpy.random import randint
randint(2,10)

6

In [32]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[0:4]

array([1, 2, 3, 4])

In [35]:
arr[1:5]

array([2, 3, 4, 5])

In [36]:
arr[5:]

array([6, 7, 8, 9])

In [37]:
arr[:5]

array([1, 2, 3, 4, 5])

In [47]:
slice_of_arr=arr[0:6]
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
#broadcasting the array
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [ ]:
#slice_of_arr is not copying the array. But having reference to the original array. In order to create
#copy of the array without referencing we use arr.copy() command.